version: '3'
services:
  main:
    build: .
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - maingo-network
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://main:8080"]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 5s

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - maingo-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - maingo-network

  grafana:
    image: grafana/grafana:5.4.4
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.ini:/etc/grafana/provisioning/datasource.ini
    networks:
      - maingo-network

networks:
  maingo-network:
    driver: bridge
