version: '3'
services:
  main:
    build: .
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - maingo-network
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://main:8080"]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 5s

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - maingo-network

networks:
  maingo-network:
    driver: bridge
