version: '3'
services:
  main:
    build: .
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - maingo-network
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - maingo-network

networks:
  maingo-network:
    driver: bridge
