global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'maingo'
    static_configs:
      - targets: ['main:8080']
  - job_name: redis_exporter
    static_configs:
    - targets: ['redis-exporter:9121']
